---
title: "InstarcarT"
author: "Miguel"
date: "27/08/2021"
output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##
```{r message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(magrittr)
library(arules)
library(arulesViz)


# 

options(scipen = 999, digits = 4)
windowsFonts("Roboto" = windowsFont("Roboto"))
source("../src/ggplot_custom_theme.R")

```


```{r message = FALSE}
load("../data/instcart_data_sample.RData")
```



```{r}
orders %>% glimpse()
order_products %>% glimpse()
product_catalog %>% glimpse()

```



```{r}
orders$order_hour_of_day <- as.numeric(orders$order_hour_of_day)
```

```{r warning=FALSE}
order_products %>% 
  left_join(product_catalog, by = "product_id") %>% 
    ggplot(aes(y = department)) +
    geom_bar(stat = 'count', fill = "#28FFBF") +
    labs(
      title =  "Productos comprados por departamento",
    ) +
    ylab("") +
    xlab("Número de productos") +
    coord_flip() +
    custom_style() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


```{r}
orders %>% 
  ggplot(aes(x = order_hour_of_day)) +
  geom_histogram(color = "#ffffff", fill = "#F43B86") +
  labs(
    title = "Distribución ordenes por horario"
  ) +
  ylab("") +
  custom_style()
```


```{r warnings=FALSE, message=FALSE}
orders %>% 
  ggplot(aes(x = days_since_prior_order)) +
  geom_histogram(color = "#ffffff", fill = "#57CC99") +
  labs(
    title = "Distribución dias desde la ultima compra"
  ) +
  ylab("") +
  custom_style()
```


```{r warnings=FALSE, message=FALSE}
order_products %>% 
  group_by(order_id) %>% 
  summarise(total_items = last(add_to_cart_order)) %>% 
  ggplot(aes(x = total_items)) +
  geom_histogram(color = "#ffffff", fill = "#911F27") +
  labs(
    title = "Distribución total productos por orden"
  ) +
  ylab("") +
  custom_style()
```

```{r warnings=FALSE, message=FALSE}
orders %>% 
  group_by(user_id) %>% 
  count() %>% 
  ggplot(aes(x = n)) +
  geom_histogram(color = "#ffffff", fill = "#79B4B7") +
  labs(
    title = "Distribución total ordenes por cliente"
  ) +
  ylab("") +
  xlab("Ordenes") +
  custom_style()
```


```{r}
order_products %>% 
  group_by(product_id) %>% 
  summarize(count = n()) %>% 
  top_n(10, wt = count) %>%
  left_join(product_catalog,by="product_id") %>%
  arrange(desc(count)) 
```


```{r}
rules_aisles <- order_products %>% 
  left_join(product_catalog, by = "product_id") %>% 
  group_by(aisle) %>% 
  count() %>% 
  ungroup() %>% 
  arrange(desc(n)) %>% 
 # filter(!aisle %in% c("fresh fruits","fresh vegetables", "packaged vegetables fruits" )) %>% 
  mutate(pct = n / sum(n),
         cumulative = cumsum(pct)) %>% 
  filter(cumulative <= 0.8) %>% 
  select(aisle) %>% 
  pull()
```

## Reglas de asociacion - Preparacion de datos

```{r}
transactionsDF <- read.transactions(file = "../data/order_products_samples.csv",
                                   format = "single",
                                   sep = ",",
                                   header = TRUE,
                                   cols = c("order_id", "department"),
                                   rm.duplicates = TRUE)


```


```{r}
inspect(transactionsDF[1:5])
```


```{r}
sizes_ <- size(transactionsDF)
summary(sizes_)
```


```{r}
quantile(sizes_, probs = seq(0,1,0.1))
```



```{r}
item_frequencies <- itemFrequency(x = transactionsDF, type = "relative") # type = absolute para ver el num. de transacciones
item_frequencies %>% sort(decreasing = TRUE) %>% head(10)
```



```{r}
support_ <- 5000 / dim(transactionsDF)[1]
itemsets <- apriori(data = transactionsDF,
                    parameter = list(support = support_,
                                     confidence=0.7,
                                     maxlen=2)) 
```

3081 itemsets que tienen un soporte mayor a 100/88371, formados por uno o dos items principalmente

```{r}
summary(itemsets)
```


```{r}
top_20_itemsets <- sort(itemsets, by = "lift", decreasing = TRUE)[1:20]
inspect(top_20_itemsets) 
```



```{r}
rules_ <- apriori(data = transactionsDF,
                  parameter = list(support = support_,
                                   confidence = 0.60,
                                   target = "rules"))
```

```{r}
plot(sort(itemsets, by='lift'),
     method="graph",
     edge.arrow.size = 0.2,
     colors = c("#6F69AC", "#E8F6EF"))

```
## Estrategia Sobre aplicacion Web

```{r}

strategy1 <- product_catalog %>%  filter(department %in% c("produce" , "dairy eggs")) %>% select(product_name) %>% pull()

products_ <- read.transactions(file = "../data/order_products_samples.csv",
                                   format = "single",
                                   sep = ",",
                                   header = TRUE,
                                   cols = c("order_id", "aisle"),
                                   rm.duplicates = TRUE)

rules_def <- vector(mode = "list",length = length(rules_aisles))

for (i in seq_along(rules_aisles)) {
  
  rule_strategy1 <- apriori(data = products_,
                    parameter = list(support = 0.0001,
                                     confidence=0.7,
                                     maxlen=4),
                    appearance = list(rhs = rules_aisles[i])) 
  
  if (length(rule_strategy1) == 0) {
    next
  } else {
    
    rules_df <- as(rule_strategy1, "data.frame") %>%
    arrange(desc(lift)) %>% 
    separate(rules, c("lhs", "rhs"), "=>") %>% 
    top_n(3)
    
    rules_def[[i]] <- rules_df
  }
  
  
  
  
}

reglas_finales <- rules_def %>% 
  bind_rows()


# filtrado_reglas <- arules::subset(x = rule_strategy1,
#                           subset = lhs %ain% strategy1)
```


```{r}

inspect(sort(rule_strategy1, by = "count", decreasing = TRUE))

```


```{r}
 rule_strategy1 <- apriori(data = products_,
                    parameter = list(support = 0.0001,
                                     confidence=0.7,
                                     maxlen=4),
                    appearance = list(rhs = "frozen meals")) 
```


```{r}
plot(sort(rule_strategy1, by='lift'),
     method="graph",
     edge.arrow.size = 0.2,
     colors = c("#6F69AC", "#E8F6EF"))

```
